name: "Composer Lint"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - "composer.json"
  push:
    branches:
      - "*.x"
    paths:
      - "composer.json"

jobs:
  composer-lint:
    name: "Composer Lint"
    uses: "doctrine/.github/.github/workflows/composer-lint.yml@2.1.0"
